replicaCount: 1

image:
  registry: docker.io
  repository: spring-with-postgres
  tag: latest
  pullPolicy: Always

ingress:
  enabled: false

service:
  type: NodePort
  port: 8080

postgresql:
  fullnameOverride: postgres
  postgresqlDatabase: spring-with-postgres
  postgresqlUsername: postgres
  postgresqlPassword: password
  service:
    port: 5432
  persistence:
    enabled: false